[package]
name = "urc_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "urc_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
hex = "0.4"

